[workspace]
members = ["cd", "joinstrings", "sim", "backspace", "different", "tools", "thelastproblem", "quadrant", "leftbeehind", "oddgnome", "treasurehunt", "lineup", "pokerhand", "bossbattle", "bitsequalizer", "basicprogramming1", "memorymatch", "chess", "guessinggame", "gamerank"]
